1-3: 1-3.exe
	./1-3.exe

1-3.exe: 1-3.o
	gcc -o 1-3.exe 1-3.o

1-3.o: 1-3.c
	gcc -c 1-3.c

1-4: 1-4.exe
	./1-4.exe

1-4.exe: 1-4.o
	gcc -o 1-4.exe 1-4.o

1-4.o: 1-4.c
	gcc -c 1-4.c

1-5: 1-5.exe
	./1-5.exe

1-5.exe: 1-5.o
	gcc -o 1-5.exe 1-5.o

1-5.o: 1-5.c
	gcc -c 1-5.c

1-6: 1-6.exe
	./1-6.exe

1-6.exe: 1-6.o
	gcc -o 1-6.exe 1-6.o

1-6.o: 1-6.c
	gcc -c 1-6.c

1-7: 1-7.exe
	./1-7.exe

1-7.exe: 1-7.o
	gcc -o 1-7.exe 1-7.o

1-7.o: 1-7.c
	gcc -c 1-7.c

1-8: 1-8.exe
	./1-8.exe

1-8.exe: 1-8.o
	gcc -o 1-8.exe 1-8.o

1-8.o: 1-8.c
	gcc -c 1-8.c

1-9: 1-9.exe
	./1-9.exe

1-9.exe: 1-9.o
	gcc -o 1-9.exe 1-9.o

1-9.o: 1-9.c
	gcc -c 1-9.c

1-10: 1-10.exe
	./1-10.exe

1-10.exe: 1-10.o
	gcc -o 1-10.exe 1-10.o

1-10.o: 1-10.c
	gcc -c 1-10.c

1-12: 1-12.exe
	./1-12.exe

1-12.exe: 1-12.o
	gcc -o 1-12.exe 1-12.o

1-12.o: 1-12.c
	gcc -c 1-12.c

1-13: 1-13.exe
	./1-13.exe

1-13.exe: 1-13.o
	gcc -o 1-13.exe 1-13.o

1-13.o: 1-13.c
	gcc -c 1-13.c

1-18: 1-18.exe
	./1-18.exe

1-18.exe: 1-18.o
	gcc -o 1-18.exe 1-18.o

1-18.o: 1-18.c
	gcc -c 1-18.c

clean:
	rm *.exe *.o