1-3: 1-3.exe
	./1-3.exe

1-3.exe: 1-3.o
	gcc -o 1-3.exe 1-3.o

1-3.o: 1-3.c
	gcc -c 1-3.c

1-4: 1-4.exe
	./1-4.exe

1-4.exe: 1-4.o
	gcc -o 1-4.exe 1-4.o

1-4.o: 1-4.c
	gcc -c 1-4.c

1-5: 1-5.exe
	./1-5.exe

1-5.exe: 1-5.o
	gcc -o 1-5.exe 1-5.o

1-5.o: 1-5.c
	gcc -c 1-5.c

clean:
	rm *.exe *.o