1-3: 1-3.exe
	./1-3.exe

1-3.exe: 1-3.o
	gcc -o 1-3.exe 1-3.o

1-3.o: 1-3.c
	gcc -c 1-3.c

1-4: 1-4.exe
	./1-4.exe

1-4.exe: 1-4.o
	gcc -o 1-4.exe 1-4.o

1-4.o: 1-4.c
	gcc -c 1-4.c

clean:
	rm *.exe *.o